version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo Installing SAM CLI
      - pip install aws-sam-cli
  build:
    commands:
      - echo Build started on `date`
      - sam build --template contact-lambda-template.yaml
      - sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name contact-lambda-stack --capabilities CAPABILITY_IAM --region $AWS_DEFAULT_REGION
  post_build:
    commands:
      - echo Build completed on `date`
      - aws cloudformation describe-stacks --stack-name contact-lambda-stack --query 'Stacks[0].Outputs[?OutputKey==`ContactApiUrl`].OutputValue' --output text > api-url.txt

artifacts:
  files:
    - api-url.txt