version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "contact-lambda-stack"
s3_bucket = "contact-lambda-deployment-bucket"
s3_prefix = "contact-lambda"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = ""